package com.mofy.app.search

import android.content.Context
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.tensorflow.lite.Interpreter
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.nio.MappedByteBuffer
import java.nio.channels.FileChannel

private const val TAG = "OnDeviceEmbedder"
private const val MODEL_FILE = "embeddinggemma_300m_embedding_int8.tflite"
private const val MODEL_URL =
    "https://huggingface.co/litert-community/embeddinggemma-300m/resolve/main/$MODEL_FILE"
private const val MAX_SEQ_LEN = 256

/**
 * On-device text embedder backed by embeddinggemma-300m (TFLite).
 *
 * The 179 MB model file is downloaded to filesDir on first call to [init] and
 * reused on subsequent launches. [embed] returns a normalized float[256] vector
 * compatible with the catalog_vec.db embeddings generated by modal_embed.py.
 *
 * TODO: Integrate SentencePiece tokenizer (Gemma vocab) so [embed] produces
 *   real Gemma token IDs. Until then [embed] returns null and semantic search
 *   degrades to FTS + genre-boost ranking (still useful). The model input
 *   signature is: input_ids int32[1,256], attention_mask int32[1,256];
 *   output: sentence_embedding float32[1,256].
 */
class OnDeviceEmbedder(private val context: Context) {

    @Volatile private var interpreter: Interpreter? = null

    /** Ensures the model is downloaded and the interpreter is loaded. Returns true on success. */
    suspend fun init(): Boolean = withContext(Dispatchers.IO) {
        if (interpreter != null) return@withContext true
        try {
            val modelFile = modelFile()
            if (!modelFile.exists()) {
                Log.i(TAG, "Downloading model ($MODEL_FILE)…")
                download(modelFile)
                Log.i(TAG, "Model downloaded: ${modelFile.length() / 1_048_576} MB")
            }
            val buf = modelFile.inputStream().channel.use { ch ->
                ch.map(FileChannel.MapMode.READ_ONLY, 0, ch.size())
            }
            interpreter = Interpreter(buf, Interpreter.Options().apply { setNumThreads(2) })
            Log.i(TAG, "Interpreter ready")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to init embedder", e)
            false
        }
    }

    /**
     * Embeds [text] and returns a normalized float[256] vector, or null.
     *
     * Returns null until the SentencePiece tokenizer is integrated, because
     * incorrect tokenization produces embeddings in a different space than
     * catalog_vec.db — useless for ranking.
     */
    @Suppress("UnusedParameter")
    suspend fun embed(text: String): FloatArray? = withContext(Dispatchers.Default) {
        // TODO: tokenize `text` with Gemma SentencePiece vocab, then run inference.
        // Returning null here causes CatalogRepository.semanticSearch() to skip the
        // embedding signal and fall back to FTS + genre-boost RRF — still useful.
        null
    }

    fun isReady(): Boolean = interpreter != null

    /** Little-endian float32 blob for storing in Room's BLOB column. */
    fun FloatArray.toEmbeddingBlob(): ByteArray {
        val buf = java.nio.ByteBuffer.allocate(size * 4).order(java.nio.ByteOrder.LITTLE_ENDIAN)
        forEach { buf.putFloat(it) }
        return buf.array()
    }

    private fun modelFile(): File = File(context.filesDir, MODEL_FILE)

    private fun download(dest: File) {
        val conn = URL(MODEL_URL).openConnection() as HttpURLConnection
        conn.connectTimeout = 15_000
        conn.readTimeout = 120_000
        try {
            conn.inputStream.use { input ->
                dest.outputStream().use { output -> input.copyTo(output, bufferSize = 65_536) }
            }
        } catch (e: Exception) {
            dest.delete()
            throw e
        } finally {
            conn.disconnect()
        }
    }
}
